pages:
  image: node:20
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public/
    - cp public/demo.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - main